services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pokemon-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
      - /var/www/html/vendor
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      CACHE_STORE: redis
      SESSION_DRIVER: array
      QUEUE_CONNECTION: sync
      REDIS_CLIENT: predis
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
    networks:
      - pokemon-net

  redis:
    image: redis:7-alpine
    container_name: pokemon-redis
    ports:
      - "6379:6379"
    networks:
      - pokemon-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pokemon-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      VITE_API_URL: http://localhost:8000/api
    depends_on:
      - backend
    networks:
      - pokemon-net

networks:
  pokemon-net:
    driver: bridge
